// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9vkTtyPMQIZE2Gd2LagvtL6HkKIZZ-E',
    appId: '1:321858639619:web:049ffc3bc2cfc15b03bb36',
    messagingSenderId: '321858639619',
    projectId: 'projectbuddyfinder',
    authDomain: 'projectbuddyfinder.firebaseapp.com',
    storageBucket: 'projectbuddyfinder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZDLefWEo-CBtin5XbFdVeexMKZppQiI',
    appId: '1:321858639619:android:040a7b655821241c03bb36',
    messagingSenderId: '321858639619',
    projectId: 'projectbuddyfinder',
    storageBucket: 'projectbuddyfinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdK_L8MLaG__zjvKLN2eNoaqSiLajlPnc',
    appId: '1:321858639619:ios:560e42e4958ae1d403bb36',
    messagingSenderId: '321858639619',
    projectId: 'projectbuddyfinder',
    storageBucket: 'projectbuddyfinder.appspot.com',
    iosBundleId: 'com.example.proddyfi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdK_L8MLaG__zjvKLN2eNoaqSiLajlPnc',
    appId: '1:321858639619:ios:560e42e4958ae1d403bb36',
    messagingSenderId: '321858639619',
    projectId: 'projectbuddyfinder',
    storageBucket: 'projectbuddyfinder.appspot.com',
    iosBundleId: 'com.example.proddyfi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm9vkTtyPMQIZE2Gd2LagvtL6HkKIZZ-E',
    appId: '1:321858639619:web:8304df8152dfb61503bb36',
    messagingSenderId: '321858639619',
    projectId: 'projectbuddyfinder',
    authDomain: 'projectbuddyfinder.firebaseapp.com',
    storageBucket: 'projectbuddyfinder.appspot.com',
  );

}